/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_player_util_FfmpegUtils */

#ifndef _Included_com_player_util_FfmpegUtils
#define _Included_com_player_util_FfmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_player_util_FfmpegUtils
 * Method:    geVideoThumbBitmap
 * Signature: (Ljava/lang/String;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_player_util_FfmpegUtils_geVideoThumbBitmap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_player_util_FfmpegUtils
 * Method:    getVideoThumbJpg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_player_util_FfmpegUtils_getVideoThumbJpg
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
